routes/web.php
<?php

//Route::get ('/register', 'RegistrationController@create');
//Route::post('/register','RegistrationController@store');



// Authentication Routes...
//Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
//Route::post('login', 'Auth\LoginController@login');
//Route::post('logout', 'Auth\LoginController@logout')->name('logout');
//// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {return view('welcome');});


Route::get('/', 'UsersController@count');
Route::post('/','UsersController@contact_us');
Route::post('/notification_for_users','UsersController@notifications_for_users');

// Home Routes ...
Route::get('/home', 'UsersController@index')->name('home')->middleware(['is_user', 'is_admin']);

// Users Routes ...
Route::get('/users/registration', 'Auth\RegisterController@registration')->name('registration');
Route::post('/register', 'Auth\RegisterController@register');

Route::get('/users/create', 'UsersController@create')->name('create_newUser')->middleware(['is_user','is_policeStation']);
Route::post('/users', 'UsersController@store');
Route::get('/users/{user}', 'UsersController@show')->name('profile');
Route::post('/users/{id}','BicyclesController@store');
Route::post('users/stolenbicycles/{bicycle_id}', 'BicyclesController@steal_report');

Route::get('/show/message/{message}', 'UsersController@show_message')->name('show_message')->middleware('is_superAdmin');
Route::get('/show/stolenbicycles/{steal_report}', 'UsersController@show_steal_report')->name('show_steal_report');
Route::get('/markAsRead','UsersController@markAsRead')->name('read');

// Admins Routes
Route::get('admins/admin_create', 'UsersController@admin_create')->name('admin_create')->middleware('is_superAdmin');
Route::get('/admins/{admin_id}', 'UsersController@admin_dashboard')->name('admin_dashboard')->middleware('is_user');
Route::post('/admins', 'UsersController@admin_store');

//PoliceStation Routes
Route::get('create/police_station', 'UsersController@create_police_station')->name('create_police_station');
Route::post('police_stations', 'UsersController@police_station_store');

// Bicycles Routes ...
Route::get('/bicycles', 'BicyclesController@index')->name('bicycles')->middleware('is_user');
Route::get('/bicycles/create/{user}', 'BicyclesController@create')->name('create_bicycles')->where('user', '[0-9]+')->middleware('is_policeStation');
//Route::post('/bicycles/{user}', 'BicyclesController@store')->name('add_bicycle')->where('user', '[0-9]+');

Route::get('/search', 'BicyclesController@search')->name('search');
Route::get('/search/users', 'UsersController@index')->name('search/users');
Route::get('/bicycles/{id}', 'BicyclesController@info')->name('information');

Route::get('/bicycles/gallery/{bicycle}','BicyclesController@showGallery')->name('gallery');
Route::post('/bicycles/gallery/{bicycle}', 'BicyclesController@upload')->name('uploads')->middleware('is_policeStation');

// Edit Routes
Route::resource('bicycles', 'BicyclesController');
Route::resource('user', 'UsersController');

app/Bicycle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;

class Bicycle extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'user_id','bicycle_type','bicycle_manufacturer','bicycle_model', 'color', 'frame_size', 'serial_number', 'is_steal'
    ];

    protected $table = 'bicycles';

    public function user(){

       return $this->belongsTo(User::class);

    }

    public function image(){

        return $this->hasMany(Image::class);

    }

    public function steal_report(){

        return $this->belongsTo(StealReport::class);

    }

    public function getFeaturedImageAttribute()
    {
        $db_image = Image::where('bicycle_id', $this->id)->first();
        if ($db_image)
        {
            return $db_image->path;
        }
    }
}

app/User.php
<?php

namespace App;

use App\Listeners\NewUserCreatedNotification;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\Debug\Exception\UndefinedFunctionException;

class User extends Authenticatable
{
    use Notifiable;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'role_id', 'admin_id', 'name', 'surname', 'email', 'password', 'residence','address','phone_number', 'birth_date', 'OIB'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $table = 'users';


    public function bicycles()
    {

        return $this->hasMany(Bicycle::class);

    }

    public function roles()
    {

        return $this->belongsTo(Role::class);

    }

//    public function users()
//    {
//
//        return $this->hasMany('User', 'admin_id');
//
//    }

    public function notifications()
    {

        return $this->hasMany(Notifications::class);

    }

//    public function messages()
//    {
//
//        return $this->hasMany(Message::class);
//
//    }

    public function steal_report()
    {

        return $this->hasMany(StealReport::class);

    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Bicycle;
use App\Events\NewMessageReceived;
use App\Events\NewUserCreatedEvent;
use App\Events\NotificationsForUsersEvent;
use App\Message;
use App\Notifications;
use App\Repositories\Users;
use App\Role;
use App\StealReport;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except('count', 'create', 'store', 'contact_us');
        $this->middleware('is_policeStation')->only('edit', 'destroy');
    }


    public function index(Request $request)
    {
        $users = User::all();

        $search = $request->input('search/users');

        $query = User::query();

        if ($search) {

            $query->where('surname', 'like', '%' . $search . '%')
                ->orWhere('residence', 'like', '%' . $search . '%')
                ->orWhere('OIB', 'like', '%' . $search . '%');

        }

        $users = $query->paginate(13);

        $admins = User::where('role_id', '2')->get();

        $notifications = Notifications::where('notification_role', 'newUser')->where('is_read', false)
            ->orderBy('created_at', 'desc')
            ->get();

        $messages = Notifications::where('notification_role', 'Message')->where('is_read', false)
            ->orderBy('created_at', 'desc')
            ->get();

        $steal_reports = Notifications::where('notification_role', 'Steal Report')->where('is_read', false)
            ->orderBy('created_at', 'desc')
            ->get();

        $new_notifications = Notifications::where('notification_role', 'newUser')->where('is_read', false)->count();
        $new_messages = Notifications::where('notification_role', 'Message')->where('is_read', false)->count();
        $new_steal_reports = Notifications::where('notification_role', 'Steal Report')->where('is_read', false)->count();

        return view('home', compact('users', 'admins', 'notifications', 'new_notifications', 'messages', 'new_messages', 'steal_reports', 'new_steal_reports'));
    }

    public function markAsRead()
    {
        Notifications::where('notification_role', 'newUser')->where('is_read', false)->update(['is_read' => true]);
        return back();
    }


    public function show_message($id)
    {

        Notifications::where('notification_role', 'Message')->where('message_id', $id)->where('is_read', false)->update(['is_read' => true]);
        $message = Message::find($id);
        return view('layouts.show_message', compact('message'));
    }

    public function show_steal_report($id)
    {

        Notifications::where('notification_role', 'Steal Report')->where('steal_report_id', $id)->where('is_read', false)->update(['is_read' => true]);
        StealReport::where('id', $id)->where('is_read', false)->update(['is_read' => true]);

        $steal_report = StealReport::find($id);
        $user = User::where('id', $steal_report->user_id)->first();
        $bicycle = Bicycle::where('id', $steal_report->bicycle_id)->first();
        return view('layouts.show_steal_report', compact('steal_report', 'user', 'bicycle'));
    }


    public function show($id, Bicycle $bicycle)
    {
        $user = User::find($id);
        if ((Auth::check() && Auth::user())) {

            return view('users.show', compact('user', 'bicycle'));

        } else {

            return back();
        }
    }


    public function create()
    {
        $users = User::where('role_id', '2')->get();
        $admin_id = \request('admin_id');

        return view('users.create', compact('users', 'admin_id'));

    }


    public function store()
    {
        $role = Role::where('name', 'user')->first();

        $user = User::create([
            'role_id' => $role->id,

            'admin_id' => Auth::user()->id,

            'name' => request('name'),
            'surname' => request('surname'),
            'email' => request('email'),
            'password' => Hash::make(request('password')),
            'residence' => request('residence'),
            'address'=> request('address'),
            'phone_number'=> request('phone_number'),
            'birth_date' => request('birth_date'),
            'OIB' => request('OIB')]);

        event(new NewUserCreatedEvent($user));

        return redirect('/home');

    }

    public function admin_create()
    {

        return view('users.admin_create');

    }

    public function admin_store()
    {

        $role = Role::where('name', 'admin')->first();

        User::create([
            'role_id' => $role->id,
            'name' => request('name'),
            'address'=> request('address'),
            'residence' => request('residence'),
            'email' => request('email'),
            'password' => Hash::make(request('password')),

        ]);

        return redirect('/home');

    }

    public function admin_dashboard($id)
    {
        $user = User::find($id);
        $users = User::where('admin_id', $user->id)->get();

        return view('users.admin_dashboard', compact('users', 'user'));
    }

    public function create_police_station(){

        return view('users.create_police_station');

    }

    public function police_station_store(){

        $role = Role::where('name', 'police_station')->first();

        User::create([
            'role_id' => $role->id,
            'name' => request('name'),
            'address'=> request('address'),
            'residence' => request('residence'),
            'email' => request('email'),
            'password' => Hash::make(request('password')),

        ]);

        return redirect('/home');

    }


    public function count()
    {

        $all_users = User::count();
        $all_bicycles = Bicycle::count();

        return view('welcome', compact('all_users', 'all_bicycles'));

    }

    public function edit($id)
    {
        //        $bicycle = Bicycle::where('id', $id)->first();
        $admins = User::where('role_id', '2')->get();
        $admin = User::find($id);
        $user = User::find($id);

        return view('users.edit_user', compact('user', 'admins', 'admin'));
    }

    public function update(Request $request, $id)
    {

        $user = User::find($id);

        $this->validate(request(), [
            'admin_id' => 'required',
            'name' => 'required',
            'surname' => 'required',
            'email' => 'required',
            'residence' => 'required']);

        $user->admin_id = $request->get('admin_id');
        $user->name = $request->get('name');
        $user->surname = $request->get('surname');
        $user->email = $request->get('email');
        $user->residence = $request->get('residence');
        $user->save();
        return redirect('home');

    }

    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return back();
    }

    public function contact_us()
    {
        $message = Message::create([
            'is_read' => false,
            'contact_name' => request('contact_name'),
            'email' => request('email'),
            'mobile_phone_number' => request('mobile_phone_number'),
            'contact_message' => request('contact_message')
        ]);

        event(new NewMessageReceived($message));
        return back();

    }

    public function notification_for_users(Request $request, User $user)
    {
        $notification_for_users = $request->get('notification_for_users');
        event(new NotificationsForUsersEvent($notification_for_users, $user));

    }
}

resources/views/users/admin_create.blade.php
@extends('app.app')

@section('content')


    <div>

        <div class="col-sm-5">

            <h1> Create New Admin </h1>

            <form method="POST" action="/admins">

             {{csrf_field()}}

                <div class="form-group">

                    <label for="name"> Name: </label>

                    <input type="text" class="form-control" id="admin_name" name="name" required>

                </div>

                <div class="form-group">

                    <label for="name"> Address: </label>

                    <input type="text" class="form-control" id="address" name="address" required>

                </div>

                <div class="form-group">

                    <label for="name"> Residence: </label>

                    <input type="text" class="form-control" id="residence" name="residence" required>

                </div>

                <div class="form-group">

                    <label for="email"> Email: </label>

                    <input type="email" class="form-control" id="email" name="email" required>

                </div>

                <div class="form-group">

                    <label for="email"> Password: </label>

                    <input type="password" class="form-control" id="password" name="password" required>

                </div>

                <div class="form-group">

                    <button type="submmit" class="btn-primary">Create</button>

                </div>

            </form>

        </div>

    </div>

@endsection

resources/views/users/admin_dashboard.blade.php
@extends('app.app')

@section('content')

@include('sidebar')


    <div class="col-md-6 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="/home">
                        <em class="fa fa-home"></em>
                    </a></li>
                <li class="active">Korisnici</li>
            </ol>
        </div><!--/.row-->

        <tr class="row">

            <table class="table">
                <thead>

                <tr>

                </tr>

                <tr>
                    <div class="col-sm-11">
                        <th>Id</th>
                        <th>Name</th>
                        <th>Surname</th>
                        <th>Residence</th>
                        <th>Birth Date</th>
                        <th>OIB</th>
                    </div>
                </tr>

                </thead>
                <tbody>

                @foreach($users as $user)
                    <tr>

                        {{--<td><img src="{{asset($bicycle->featured_image) }}"/>resize(200, 200)</td>--}}
                        <td>{{$user->id}}</td>
                        <td>{{$user->name}}</td>
                        <td>{{$user->surname}}</td>
                        <td>{{$user->residence}}</td>
                        <td>{{$user->birth_date}}</td>
                        <td>
                            <a href="{{ route('profile',['id' => $user->id])}}">
                                {{$user->OIB}}
                            </a>
                        </td>

                        <td><a href="{{action('UsersController@edit', $user['id'])}}" class="btn btn-warning">Edit</a></td>

                        <td>
                            <form action="{{action('UsersController@destroy', $user['id'])}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>

                    </tr>
                @endforeach


                </tbody>

            </table>

    </div>
    </div>


@endsection

resources/views/users/create.blade.php
@extends('app.app')

@section('content')

    <div>

        <div class="col-sm-4">

            <form method="POST" action="/users">

                {{csrf_field()}}


                <div class="form-group-sm">

                    <label for="name"> Name: </label>

                    <input type="text" class="form-control" id="name" name="name" required>

                </div>

                <br>
                <div class="form-group-sm">

                    <label for="name"> Surname: </label>

                    <input type="text" class="form-control" id="surname" name="surname" required>

                </div>
                <br>

                <div class="form-group-sm">

                    <label for="email"> Email: </label>

                    <input type="email" class="form-control" id="email" name="email" required>

                </div>
                <br>

                <div class="form-group-sm">

                    <label for="password"> Password: </label>

                    <input type="password" class="form-control" id="password" name="password" required>

                </div>
                <br>

                <div class="form-group-sm">

                    <label for="name"> Residence: </label>

                    <input type="text" class="form-control" id="residence" name="residence" required>

                </div>
                <br>

                <div class="form-group-sm">

                    <label for="name"> Address: </label>

                    <input type="text" class="form-control" id="address" name="address" required>

                </div>
                <br>

                <div class="form-group-sm">

                    <label for="name"> Phone Number: </label>

                    <input type="tel" class="form-control" id="phone_number" name="phone_number" required>

                </div>
                <br>
                <div class="form-group-sm">

                    <label for="name"> Birth Date: </label>

                    <input type="date" class="form-control" id="birth_date" name="birth_date" required>

                </div>
                <br>

                <div class="form-group-sm">

                    <label for="name"> OIB: </label>

                    <input type="number" class="form-control" id="OIB" name="OIB" required>

                </div>
                <br>

                <div class="form-group">

                    <button type="submmit" class="btn-primary">Register</button>

                </div>

            </form>

        </div>


    </div>

@endsection

resources/views/users/create_police_station.blade.php
@extends('app.app')

@section('content')


    <div>

        <div class="col-sm-5">

            <h1> Kreiraj Policijsku Postaju </h1>

            <form method="POST" action="/police_stations">

                {{csrf_field()}}

                <div class="form-group">

                    <label for="name"> Name: </label>

                    <input type="text" class="form-control" id="admin_name" name="name" required>

                </div>

                <div class="form-group">

                    <label for="name"> Address: </label>

                    <input type="text" class="form-control" id="address" name="address" required>

                </div>

                <div class="form-group">

                    <label for="name"> Residence: </label>

                    <input type="text" class="form-control" id="residence" name="residence" required>

                </div>

                <div class="form-group">

                    <label for="email"> Email: </label>

                    <input type="email" class="form-control" id="email" name="email" required>

                </div>

                <div class="form-group">

                    <label for="email"> Password: </label>

                    <input type="password" class="form-control" id="password" name="password" required>

                </div>

                <div class="form-group">

                    <button type="submmit" class="btn-primary">Create</button>

                </div>

            </form>

        </div>

    </div>

@endsection

resources/views/users/index.blade.php
@extends('app.app')

@section('content')

    <div class="col-sm-8 blog-main">

        @foreach($users as $user)

            @include('users.home')

        @endforeach



    </div>

@endsection

resources/views/users/show.blade.php
@extends('app.app')

@section('content')

@include('sidebar')


    <div class="col-md-6 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <div class="row">
            <ol class="breadcrumb">
                <li><a href="/home">
                        <em class="fa fa-home"></em>
                    </a></li>
                <li class="active"> {{$user->name}} {{$user->surname}}</li>
            </ol>
        </div><!--/.row-->

        @include('layouts.user_information')

        <div class="panel-heading">
            Registrirani Bicikli


        </div>

        <button style="margin-left: 93%"  href="#" class="btn btn-info" id="add_new_bicycle"
                data-toggle="modal"
                data-target="#myModal"><i class="fa fa-plus"
                                          aria-hidden="true"></i> Dodaj
        </button>

        @include('layouts.add_bicycle')

        <table class="table" id="bicycles">
            <thead>

            <tr>
                <div class="col-sm-11">
                    <th>Id</th>
                    <th>Tip Bicikla</th>
                    <th>Proizvođać Bicikla</th>
                    <th>Boja</th>
                    <th>Veličina Rame</th>
                    <th>Serijski Broj </th>
                    <th>Galerija Slika</th>
                    <th></th>
                    <th></th>
                    <th class="text-center"> Prijava Krađe </th>
                </div>
            </tr>

            </thead>
            <tbody>

            @foreach($user->bicycles as $bicycle)
                <tr>
                    <td>{{$bicycle->id}}</td>
                    <td>{{$bicycle->bicycle_type}}</td>
                    <td>{{$bicycle->bicycle_manufacturer}}</td>
                    <td>{{$bicycle->color}}</td>
                    <td>{{$bicycle->frame_size}}</td>
                    <td>{{$bicycle->serial_number}}</td>
                    <td>

                        @if($bicycle->featured_image)
                            <div class="profile-userpic">

                                <a href="{{ route('gallery',['id' => $bicycle->id])}}">

                                    <img src="{{ asset($bicycle->featured_image) }}" class="img-responsive" alt="">

                                </a>
                            </div>
                        @else()
                            <button class="img-circle" style="margin: 15%; border-radius: 80%  ">

                                <a href="{{ route('gallery',['id' => $bicycle->id])}}">

                                    <section class="fa fa-plus"></section>

                                </a>
                            </button>
                        @endif
                    </td>

                    <td>

                        <a href="{{action('BicyclesController@edit', $bicycle['id'])}}"
                           class="btn btn-warning">Edit</a>

                    </td>
                    <td>
                        <form action="{{action('BicyclesController@destroy', $bicycle['id'])}}" method="post">
                            {{csrf_field()}}
                            <input name="_method" type="hidden" value="DELETE">
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </td>

                    <td>
                        <button href="#" class="center-block" id="create_steal_report"
                                data-toggle="modal"
                                data-target="#steal_report"><i class="fa fa-exclamation"
                                                               aria-hidden="true"></i></button>
                    </td>

                </tr>
            @endforeach
            </tbody>

        </table>

        @include('layouts.steal_report')

        <script
                src="https://code.jquery.com/jquery-1.11.1.min.js"
                integrity="sha256-VAvG3sHdS5LqTT+5A/aeq/bZGa/Uj04xKxY8KM/w9EE="
                crossorigin="anonymous"></script>

        <script>
            $(document).ready(function (event) {

                $('#add_button').click(function (event) {
                    var user_id = $('#user_id').val();
                    var bicycle_type = $('#bicycle_type').val();
                    var bicycle_manufacturer = $('#bicycle_manufacturer').val();
                    var bicycle_model = $('#bicycle_model').val();
                    var color = $('#color').val();
                    var frame_size = $('#frame_size').val();
                    var serial_number = $('#serial_number').val();
                    var is_steal = $('#is_steal').val();

                    if (bicycle_manufacturer == "") {
                        alert('Bicycle Manufacturer is required');
                    }
                    if (bicycle_type == "") {
                        alert('Bicycle Type is required');
                    }
                    if (bicycle_model == "") {
                        alert('Bicycle Model is required');
                    }
                    if (bicycle_type < '5') {
                        alert('Bicycle Type must be minimum 5 characters. Please check your input. ');
                    }
                    if (color == "") {
                        alert('Color is required, please enter.');
                    }
                    if (frame_size == "") {
                        alert('Frame Size is required, please make input.');
                    }
                    if (serial_number == "") {
                        alert('Serial Number is required');
                    }
                    $.post('', {
                        'user_id': user_id,
                        'bicycle_manufacturer': bicycle_manufacturer,
                        'bicycle_type': bicycle_type,
                        'bicycle_model': bicycle_model,
                        'color': color,
                        'frame_size': frame_size,
                        'serial_number': serial_number,
                        'is_steal': is_steal => 0,
                        '_token': $('input[name=_token]').val()
                    }, function (data) {
                        window.location.reload();
                        console.log(data);

                    });
                });
            });
        </script>

        <script>
            $(document).ready(function (event) {

                $('#send_steal_report').click(function (event) {
                    var user_id = $('#user_id').val();
                    var bicycle_id = $('#bicycle_id').val();
                    var bicycle_information = $('#bicycle_information').val();
                    var steal_date = $('#steal_date').val();
                    var steal_location = $('#steal_location').val();
                    var steal_description = $('#steal_description').val();
                    var is_read = $('#is_read').val();

                    $.post('stolenbicycles/{{$bicycle->id}}', {
                        'user_id': user_id,
                        'bicycle_id': bicycle_id,
                        'bicycle_information': bicycle_information,
                        'steal_date': steal_date,
                        'steal_location': steal_location,
                        'steal_description': steal_description,
                        'is_read': is_read => 0,
                        '_token': $('input[name=_token]').val()
                    }, function (data) {
                        window.location.reload();
                        console.log(data);
                    });
                });
            });

        </script>
    </div>
    </div>
    </div>
@endsection